export const sampleDemoReport = {
  video_info: {
    filename: "示例演讲视频.mp4",
    duration: 58,
    fps: 30,
    width: 1280,
    height: 720,
    mock_mode: false,
    demo_sample: true,
  },
  transcript: {
    text:
      "大家好，今天我想分享的是人工智能如何帮助我们提升公众表达。首先，AI 可以把演讲内容转成文字，让我们看到结构是否清楚。其次，系统可以观察手势、站姿和镜头交流，帮助我们发现平时不容易注意到的小问题。最后，我认为技术不是替代练习，而是让每一次练习都有反馈、有方向。以上就是我的分享，谢谢大家。",
    raw_text:
      "大家好今天我想分享的是人工智能如何帮助我们提升公众表达首先AI可以把演讲内容转成文字让我们看到结构是否清楚其次系统可以观察手势站姿和镜头交流帮助我们发现平时不容易注意到的小问题最后我认为技术不是替代练习而是让每一次练习都有反馈有方向以上就是我的分享谢谢大家",
    source: "sample_demo",
    polish_source: "sample_demo",
    polish_error: null,
    mock_mode: false,
    speech_rate_reliable: true,
    word_count: 132,
    speech_rate: 137,
    duration: 58,
    filler_words: {
      然后: 1,
    },
    filler_total: 1,
    logic_words_count: 4,
    has_opening: true,
    has_ending: true,
    has_topic: true,
    structure_analysis: {
      opening: { detected: true, reason: "开头直接说明主题，听众能快速进入内容。" },
      ending: { detected: true, reason: "结尾有总结和感谢，收束清楚。" },
      topic: { detected: true, reason: "主题集中在 AI 对公众表达训练的帮助。" },
    },
  },
  visual_metrics: {
    mock_mode: false,
    fallback_mode: "sample_demo",
    analysis_note: "示例视频已完成姿态、手势和镜头交流分析。",
    face_visible_ratio: 0.94,
    looking_camera_ratio: 0.74,
    head_down_count: 2,
    body_sway_score: 86,
    gesture_activity: 0.46,
    hand_visible_ratio: 0.72,
    face_block_count: 0,
    expression_change_score: 68,
    analysis_frame_count: 52,
    sample_interval_seconds: 1,
    head_down_events: ["00:18", "00:41"],
    face_block_events: [],
  },
  scores: {
    content: 84,
    voice: 82,
    gesture: 78,
    posture: 86,
    camera_contact: 80,
    overall: 82,
  },
  suggestions: [
    "开头主题明确，可以继续保留这种直接进入主题的方式。",
    "语速整体稳定，重点句前后可以再增加半秒停顿。",
    "手势能配合观点表达，建议在列举三点时让动作更有层次。",
    "镜头交流比例较好，低头看稿的位置可以再靠近镜头高度。",
  ],
  issues: [
    {
      time: "00:18",
      title: "短暂低头",
      description: "这一处出现短暂低头，可以把提纲放到更接近镜头的位置。",
      severity: "轻微",
    },
    {
      time: "00:34",
      title: "重点句停顿略短",
      description: "讲到第二个观点后可以停顿一下，让听众更容易跟上结构。",
      severity: "建议",
    },
  ],
  summary: "本次演讲结构完整、语速稳定，镜头交流和身体姿态表现较好，可以继续打磨重点停顿和手势层次。",
  analysis_status: {
    upload: {
      mode: "sample",
      file_size: 18100000,
      message: "已使用内置示例视频完成体验流程。",
    },
    speech: {
      mode: "sample",
      message: "示例视频语音转写已完成。",
    },
    visual: {
      mode: "sample_demo",
      message: "示例视频已完成 52 帧视觉关键点分析。",
    },
  },
};
